apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: docker-gs-ping-hpa
  namespace: apeterson30
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: docker-gs-ping-statefulset
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
