apiVersion: v1
kind: Service
metadata:
  name: docker-gs-ping-service
  namespace: apeterson30
spec:
  type: LoadBalancer
  selector:
    app: docker-gs-ping
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: secondary
      protocol: TCP
      port: 30010
      targetPort: 30010
